// Generated by CoffeeScript 1.3.3
(function() {
  var app, assets, express, http, path, routes, server;

  http = require('http');

  path = require('path');

  express = require('express');

  assets = require('connect-assets');

  require('express-namespace');

  app = express();

  app.configure(function() {
    app.locals({
      root: process.env.APP_ROOT || __dirname,
      port: process.env.PORT || 3000,
      title: 'ExpressJS'
    });
    app.set('views', path.join(app.locals.root, 'views'));
    app.set('view engine', 'jade');
    app.use(express.favicon());
    app.use(express.logger('dev'));
    app.use(express.bodyParser());
    app.use(express.methodOverride());
    app.use(express["static"](path.join(app.locals.root, 'public')));
    app.use(assets());
    return app.use(app.router);
  });

  app.configure('development', function() {
    return app.use(express.errorHandler());
  });

  routes = require(path.join(app.locals.root, 'routes'));

  app.get('/', routes.index);

  server = http.createServer(app);

  server.listen(app.locals.port, function() {
    return console.log("NodeJS is listening on port " + app.locals.port);
  });

}).call(this);
