// Generated by CoffeeScript 1.3.3
(function() {
  var app, assets, express, http, path, routes, server;

  http = require('http');

  path = require('path');

  express = require('express');

  assets = require('connect-assets');

  require('express-namespace');

  app = express();

  app.configure(function() {
    app.set('root', process.env.APP_ROOT || __dirname);
    app.set('port', process.env.PORT || 3000);
    app.set('views', path.join(app.get('root'), 'views'));
    app.set('view engine', 'jade');
    app.use(express.favicon());
    app.use(express.logger('dev'));
    app.use(express.bodyParser());
    app.use(express.methodOverride());
    app.use(express["static"](path.join(app.get('root'), 'public')));
    app.use(assets());
    return app.use(app.router);
  });

  app.configure('development', function() {
    return app.use(express.errorHandler());
  });

  routes = require(path.join(app.get('root'), 'routes'));

  app.get('/', routes.index);

  server = http.createServer(app);

  server.listen(app.get('port'), function() {
    return console.log("NodeJS is listening on port " + (app.get('port')));
  });

}).call(this);
