// Generated by CoffeeScript 1.3.3
(function() {
  var http, port, server;

  http = require('http');

  port = process.env.PORT || 3000;

  server = http.createServer(function(req, res) {
    res.writeHead(200, {
      'Content-Type': 'text/plain'
    });
    return res.end("NodeJS version " + process.version + " is running");
  });

  server.listen(port, function() {
    return console.log("NodeJS is listening on port " + port);
  });

}).call(this);
